---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: test
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: kafka
  namespace: test
spec:
  serviceName: kafka-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kafka
              topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
             - weight: 1
               podAffinityTerm:
                 labelSelector:
                    matchExpressions:
                      - key: "app"
                        operator: In
                        values:
                        - zk
                 topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      containers:
      - name: kafka
        image: siangyeh8818/kafka:test-12
        ports:
        - containerPort: 9092
        env:
        - name: ZOOKEEPER
          value: "zk-0.zk-svc.test.svc.cluster.local:2181,zk-1.zk-svc.test.svc.cluster.local:2181,zk-2.zk-svc.test.svc.cluster.local:2181"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
 #       - name: KAFKA_ADVERTISED_LISTENERS
 #         value: "kafka-0.kafka-svc.test.svc.cluster.local"
 #       - name: INTERNAL_LISTENERS
 #         value: "kafka-0.kafka-svc.test.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: log
          mountPath: /tmp
        resources:
          requests:
            memory: "1Gi"
            cpu: 500m
        securityContext:
          privileged: true
      volumes:
      - name: log
        hostPath:
          path: /opt/kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-nodeport
  namespace: test
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - targetPort: 9092
    port: 9092
    nodePort: 30012
  selector:
    app: kafka
