apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-nodeport
  namespace: monitor
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - targetPort: 9093
    port: 9093
    nodePort: 30010
  selector:
    app: kafka
