---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc-load
  namespace: monitor
  labels:
    app: kafka
spec:
  ports:
  - port: 9093
    targetPort: 9093
    name: server
  selector:
    app: kafka
