---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc-nodeport
  namespace: monitor
  labels:
    app: zk-svc
spec:
  type: NodePort
  ports:
  - port: 2888
    targetPort: 2181
    nodePort: 30011
  selector:
    app: zk
